decide/base/urls.py
from django import views
from django.urls import path
from . import views


urlpatterns = [
    path('', views.welcome, name='index'),
]

decide/decide/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title='Decide API')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', include('base.urls')),
    path('doc/', schema_view),
    path('gateway/', include('gateway.urls')),
    path('users/', include('users.urls')),
    path('mailer/', include('mailer.urls')),
    path('', include('base.urls')),
    path('ticket/', include('ticket.urls'))

]

for module in settings.MODULES:
    urlpatterns += [
        path('{}/'.format(module), include('{}.urls'.format(module)))
    ]

decide/users/urls.py
from django.urls import path

from .views import RegisterView, LoginView, LogoutView, RequestPasswordReset, ChangePassword, CertLoginView, EditProfileView, NoticeView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/', RequestPasswordReset.as_view(), name='password_reset'),
    path('change-password/<str:uidb64>/<str:token>/', ChangePassword.as_view(), name='change_password'),
    path('notice/', NoticeView.as_view(), name='notice'),
    path('cert-login/', CertLoginView.as_view(), name='cert_login'),
    path('edit-profile/', EditProfileView.as_view(), name='edit_profile'),
]

decide/users/forms.py
from django import forms
from django.contrib.auth.models import User
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.serialization import pkcs12
from cryptography.x509 import NameOID

class EmailForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'usuario@dominio.com'}))

class PasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': '********'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': '********'}))

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        # Verificar que las contraseñas coincidan
        if password and confirm_password and password != confirm_password:
            self.add_error('password', 'Las contraseñas no coinciden.')
            self.add_error('confirm_password', 'Las contraseñas no coinciden.')

        # Verificar si la contraseña cumple con ciertos criterios (puedes personalizar esto)
        if password and len(password) < 8 and len(self.errors) == 0:
            self.add_error('password', 'La contraseña debe tener al menos 8 caracteres.')

        # Verificar si la contraseña es lo suficientemente fuerte según tus criterios
        if password and len(self.errors) == 0:
            if not any(char.isdigit() for char in password) and len(self.errors) == 0:
                self.add_error('password', 'La contraseña debe contener al menos un número.')

            elif not any(char.isupper() for char in password) and len(self.errors) == 0:
                self.add_error('password', 'La contraseña debe contener al menos una letra mayúscula.')

            elif not any(char.islower() for char in password) and len(self.errors) == 0:
                self.add_error('password', 'La contraseña debe contener al menos una letra minúscula.')

            elif not any(char in "!@#$%^&*()-_=+[]{}|;:'\",.<>?/" for char in password) and len(self.errors) == 0:
                self.add_error('password', 'La contraseña debe contener al menos un carácter especial.')

        return cleaned_data



class CertificateLoginForm(forms.Form):
    cert_file = forms.FileField(label='Certificate File', required=True)
    cert_password = forms.CharField(label='Certificate Password', widget=forms.PasswordInput, required=True)

    def get_or_create_user(self):
        try:
            if not self.is_valid():
                return None

            cert_content = self.cleaned_data['cert_file'].read()
            cert_password = self.cleaned_data['cert_password']

            _, cert, _ = pkcs12.load_key_and_certificates(cert_content, cert_password.encode('utf-8'), backend=default_backend())

            cert_json = {
                'subject': cert.subject.get_attributes_for_oid(NameOID.COMMON_NAME)[0].value,
            }


            if '-' in cert_json['subject']:
                subject_name = cert_json['subject'].split('-')[0].strip()
                subject_name_without_spaces = subject_name.replace(" ", "")
            else:
                subject_name = cert_json['subject'].strip()
                subject_name_without_spaces = subject_name.replace(" ", "")

            user, _ = User.objects.get_or_create(username=subject_name_without_spaces)

            return user

        except Exception:
            return None

decide/users/views.py
from datetime import datetime
import re
from urllib.parse import urlencode

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMultiAlternatives
from django.core.exceptions import MultipleObjectsReturned
from django.conf import settings

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import TemplateView
from census.models import Census
from store.models import Vote
from voting.models import Voting
from rest_framework import status
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.views import APIView
from users.forms import EmailForm, PasswordForm
from decide import settings
from django.db import IntegrityError
from django.utils.translation import gettext as _
from .forms import CertificateLoginForm
from django.contrib.auth.backends import ModelBackend
from django.views.generic import TemplateView
from base import mods
import json
from django.http import Http404



class RegisterView(APIView):
    def get(self, request):
        context = {'is_mobile': request.user_agent.is_mobile}
        if request.user_agent.is_mobile:
            return render(request, 'users/register_mobile.html', context)
        else:
            return render(request, 'users/register.html')

    def post(self, request):
        username = request.data.get('username', '')
        password = request.data.get('password', '')
        confirm_password = request.data.get('confirm_password', '')
        email = request.data.get('email', '') 

        if not username or not password or not confirm_password:
            if request.user_agent.is_mobile:
                return render(request, 'users/register_mobile.html', {'error': _('Nombre de usuario y contraseña son obligatorios.'), 'is_mobile': request.user_agent.is_mobile})
            else:
                return Response({'error': _('Username and password are required.')}, status=status.HTTP_400_BAD_REQUEST)
        
        if password != confirm_password:
            if request.user_agent.is_mobile:
                return render(request, 'users/register_mobile.html', {'error': _('Las contraseñas no coinciden.'), 'is_mobile': request.user_agent.is_mobile})
            else:
                return render(request, 'registration/register_fail.html', {'error': _('The passwords do not match.')})
        
        try:
            user = User.objects.create_user(username, password=password, email=email)
            if request.user_agent.is_mobile:
                return redirect('/')
            else:
                return render(request, 'registration/register_success.html', {'message': _('Successful registration. You are now registered.')})   
        except IntegrityError:
            if request.user_agent.is_mobile:
                return render(request, 'users/register_mobile.html', {'error': _('El nombre de usuario ya está en uso.'), 'is_mobile': request.user_agent.is_mobile})
            else:
                return render(request, 'registration/register_fail.html', {'error': _('The username is already in use.')})   



class LoginView(APIView):
    template_name = 'users/login.html'

    def get(self, request):
        user = request.user
        if request.user_agent.is_mobile:
            return render(request, 'users/login_mobile.html', {'user': user, 'is_mobile': request.user_agent.is_mobile})
        else:
            return render(request, self.template_name, {'user': user})

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            if request.user_agent.is_mobile:
                return render(request, 'users/login_mobile.html', {'error': _('Credenciales inválidas'), 'is_mobile': request.user_agent.is_mobile})
            else:
                return render(request, self.template_name, {'error': _('invalid credentials')})

class LogoutView(APIView):
    def post(self, request):
        logout(request)
        return redirect('/')
    
    def get(self,request):
        logout(request)
        return redirect('/')

class RequestPasswordReset(APIView):
    def post(self, request):
        form = EmailForm(request.POST)
        if form.is_valid():
            try:
                user = get_object_or_404(User, email=form.cleaned_data['email'])
            except:
                if request.user_agent.is_mobile:
                    return render(request, 'registration/make_petition_form_mobile.html', {'is_mobile': request.user_agent.is_mobile, 'error': _('No existe un usuario con ese correo electrónico.')})
                else:
                    return Response({'error': _('There is no user with that email.')}, status=status.HTTP_400_BAD_REQUEST)
                

            if self.validate_email(user.email):
                # Generar el token único
                token = default_token_generator.make_token(user)

                # Generar la URL de verificación por correo electrónico
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                new_password_url = reverse('users:change_password', args=[uid, token])

                # Enviar el correo electrónico de verificación
                template = get_template('registration/password_email.html')
                content = template.render({'new_password_url': settings.BASEURL + new_password_url, 'username': user.username})
                message = EmailMultiAlternatives(
                    'Cambio de contraseña',
                    content,
                    settings.EMAIL_HOST_USER,
                    [user.email]
                )

                message.attach_alternative(content, 'text/html')
                message.send()
                return redirect('/')

        return Response(form.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request):
        form = EmailForm()
        if request.user_agent.is_mobile:
            return render(request, 'registration/make_petition_form_mobile.html', {'form': form, 'is_mobile': request.user_agent.is_mobile})
        else:
            return render(request, 'registration/make_petition_form.html', {'form': form})

    def validate_email(self, email):
        patron = r'^[\w\.-]+@[\w\.-]+\.\w+$'
        if re.match(patron, email):
            return True
        else:
            return False



class ChangePassword(APIView):
    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)
        if user is not None and default_token_generator.check_token(user, token):
            form = PasswordForm()
            return render(request, 'registration/change_password_form.html', {'form': form})
        else:
            return render(request, 'registration/petition_new_password_error.html')

    def post(self, request, uidb64, token):
        user = self.get_user(uidb64)
        if user is not None and default_token_generator.check_token(user, token):
            form = PasswordForm(request.POST)
            form.old_password = user.password
            if form.is_valid():
                user.password = make_password(form.cleaned_data['password'])
                user.save()
                return redirect('/')
            else:
                return render(request, 'registration/change_password_form.html', {'form': form})
        else:
            return render(request, 'registration/petition_new_password_error.html')

    def get_user(self, uidb64):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        return user


class CertLoginView(APIView):
    template_name = 'registration/cert_login.html'

    def get(self, request, *args, **kwargs):
        cert_form = CertificateLoginForm()
        if request.user_agent.is_mobile:
            return render(request, 'registration/cert_login_mobile.html', {'cert_form': cert_form, 'is_mobile': request.user_agent.is_mobile})
        else:
            return render(request, self.template_name, {'cert_form': cert_form})

    def post(self, request, *args, **kwargs):
        cert_form = CertificateLoginForm(request.POST, request.FILES)
        if cert_form.is_valid():
            user = cert_form.get_or_create_user()
            if user:
                backend = ModelBackend()
                user.backend = "%s.%s" % (backend.__module__, backend.__class__.__name__)
                login(request, user)
                if request.user_agent.is_mobile:
                    return redirect('/')
                else: 
                    return render(request, 'registration/cert_success.html', {'user': user})
            else:
                if request.user_agent.is_mobile:
                    return render(request, 'registration/cert_login_mobile.html', {'is_mobile': request.user_agent.is_mobile, 'error': _('Credenciales inválidas')})
                else:
                    return render(request, 'registration/cert_fail.html')

        return render(request, 'registration/cert_fail.html')


class EditProfileView(TemplateView):
    template_name = 'users/edit_profile.html'

    def get_template_names(self):
        if self.request.user_agent.is_mobile:

decide/users/templates/users/edit_profile_mobile.html
{% extends "base.html" %}
{% load i18n static %}

{% block extrahead %}
    <link type="text/css" rel="stylesheet" href="https://unpkg.com/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link type="text/css" rel="stylesheet" href='{% static "users/style.css" %}' />
{% endblock %}

{% block content %}
    <div id="app-visualizer">

        {% if not user.is_authenticated %}

            <h1 class="voting-title">{% trans 'Inicia sesión para poder editar tu perfil' %}</h1>

            <div class="login-container-mobile">
                <a href="/users/login/" class="btn-mobile">{% trans 'Iniciar sesión' %}</a>
            </div>

        {% elif user.is_superuser %}
            
            <div class="edit-admin-container-mobile">
                <h2 class="edit-admin-mobile">{% trans 'No puedes editar tus datos siendo administrador.' %}</h2>
            </div>

        {% else %}

            <h1 class="edit-title-mobile">{% trans 'Editar datos de usuario' %}</h1>

            <form method="post" class="form-mobile">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="label-mobile">{% trans 'Nombre de usuario' %}</label>
                    <input id="id_username" type="text" name="username" value="{{ user.username }}" class="form-control">
                </div>
                
                <div class="form-group">
                    <label for="first_name" class="label-mobile">{% trans 'Nombre' %}</label>
                    <input id="id_first_name" type="text" name="first_name" value="{{ user.first_name }}" class="form-control">
                </div>
            
                <div class="form-group">
                    <label for="last_name" class="label-mobile">{% trans 'Apellidos' %}</label>
                    <input id="id_last_name" type="text" name="last_name" value="{{ user.last_name }}" class="form-control">
                </div>
                
                <div class="form-group">
                    <label for="email" class="label-mobile">{% trans 'Correo electrónico' %}</label>
                    <input id="id_email" type="email" name="email" value="{{ user.email }}" class="form-control">
                </div>

                <p class="error-mobile" id="error-message-mobile">{{ error }}</p>
                <button type="submit" class="btn-mobile">{% trans 'Actualizar datos' %}</button>
            </form>

        {% endif %}

    </div>
{% endblock %}

decide/users/templates/users/login.html
{% extends "base.html" %}
{% load i18n static %}

{% load static %}
{% block extrahead %}
    <title>Iniciar Sesión</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
{% endblock extrahead %}

{% block content %}
    <div class="container">
        <div class="card form-container">
            <div class="card-body">
                <h2 class="card-title">{% trans "Login" %}</h2>
                {% if not user.is_authenticated %}
                    <p class="card-text">{% trans "¿Don´t have account?" %}<a href="{% url 'users:register' %}">{% trans "Sign up" %}</a></p>
                {% endif %}
                {% if user.is_authenticated %}
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link">{% trans "Logout" %}</button>
                    </form>
                {% endif %}
                {% if not user.is_authenticated %}
                
                    <form method="post" action="{% url 'users:login' %}" class="mt-3">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="username">{% trans "Username:" %}</label>
                            <input type="text" name="username" class="form-control" required>
                        </div>

                        <div class="form-group">
                            <label for="password">{% trans "Password" %}</label>
                            <input type="password" name="password" class="form-control" required>
                        </div>


                        <div class="login-button" style="display: flex; justify-content: space-between;">
                            <button type="submit" class="btn btn-primary">{% trans "Login" %}</button>
                            <a href="{% url 'users:password_reset' %}" style="margin-top: 15px;">¿Olvidó su contraseña?</a>
                            <a href="{% url 'social:begin' 'google-oauth2' %}" style="margin-top: 15px;">Iniciar sesión con Google</a>
                            <a href="{% url 'users:cert_login' %}" style="margin-top: 15px;">Iniciar sesión con Certificado Digital</a>
                        </div>
                    </form>

                    {% if error %}
                        <p class="mt-3 text-danger">{{ error }}</p>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% endblock content %}
    

decide/users/templates/users/login_mobile.html
{% extends "base.html" %}
{% load i18n static %}

{% block extrahead %}
    <link type="text/css" rel="stylesheet" href="https://unpkg.com/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link type="text/css" rel="stylesheet" href='{% static "users/style.css" %}' />
{% endblock %}

{% block content %}
    <div id="app-visualizer">

        {% if user.is_authenticated %}
            <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn-mobile">{% trans 'Cerrar sesión' %}</button>
            </form>
        {% endif %}

        {% if not user.is_authenticated %}

            <h1 class="register-title-mobile">{% trans 'Iniciar sesión' %}</h1>

            <form method="post" action="{% url 'users:login' %}" class="form-mobile">
                {% csrf_token %}

                <div class="form-group">
                    <label for="username" class="label-mobile">{% trans 'Nombre de usuario' %}</label>
                    <input id="id_username" type="text" name="username" class="form-control" required>
                </div>

                <div class="form-group">
                    <label for="password" class="label-mobile">{% trans 'Contraseña' %}</label>
                    <input id="id_password" type="password" name="password" class="form-control" required>
                </div>

                {% if not user.is_authenticated %}
                    <h3>¿No tienes una cuenta? <a href="{% url 'users:register' %}"> {% trans 'Regístrate' %}</a></h3>
                {% endif %}

                <p class="error-mobile" id="error-message-mobile">{{ error }}</p>
                <button type="submit" class="btn-mobile">{% trans 'Iniciar sesión' %}</button>

                <h3>¿Olvidó su contraseña? <a href="{% url 'users:password_reset' %}"> {% trans 'Recuperar contraseña' %}</a></h3>

                <div class="subtitle-line-mobile"></div>

                <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn-mobile">{% trans 'Iniciar sesión con Google' %}</a>
                <a href="{% url 'users:cert_login' %}" class="btn-mobile">{% trans 'Iniciar sesión con Certificado Digital' %}</a>

            </form>
        
        {% endif %}

    </div>
{% endblock %}

decide/users/templates/users/notice.html
{% extends "base.html" %}

{% load i18n static %}

{% load static %}
{% block extrahead %}
    <title>Notificaciones</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../../static/users/style.css">
    
{% endblock extrahead %}

{% block content %}
  <h1 class="voting-title">Notificaciones de las votaciones</h1>
  
  <form method="get" action="{% url 'users:notice' %}">
    <div class="form-group">
      <input type="text" id="name" name="name" class="form-filter" placeholder="Buscar" value="{{ request.GET.name }}">
    </div>
    <div class="columna">
      <label for="date" class="form-label">Filtrado:</label>
      <div id="date" class="input-group">
        <input type="date" id="start_date" name="start_date" class="form-filter" min="{{ today|date:'Y-m-d' }}" value="{{ request.GET.start_date }}">
        <input type="date" id="end_date" name="end_date" class="form-filter" min="{{ today|date:'Y-m-d' }}" value="{{ request.GET.end_date }}">
      </div>
    </div>
    <button type="submit">{% trans 'Filter' %}</button>
  </form>


  {% if voting_info %}
    <div class="voting-cards">
      {% for info in voting_info %}
        <div class="voting-card" onclick="redirigir({{ info.voting_id }}, {{ info.has_voted_str }}, '{{ info.status }}')">
          <h3>{{ info.voting_name }}</h3>
          <p><strong>Estado de la votación:</strong> {{ info.status }}</p>
          {% if info.has_voted %}
            <p><strong>¡Ya has votado!</strong></p>
          {% else %}
            <p><strong>Aún no has votado</strong></p>
          {% endif %}
        </div>

      {% endfor %}
    </div>
  {% else %}
    <p>{% trans 'You are not associated with any voting notices.' %}</p>
  {% endif %}

  <script>
    function redirigir(id, hasVoted, status) {
      console.log(status + hasVoted)
      if (!hasVoted && status == "La votación sigue Abierta") {
        window.location.href = "/booth/" + id;
      } else {
        window.location.href = "/visualizer/" + id;
      }
    }

        // Validación para fechas
        var startDateInput = document.getElementById('start_date');
    var endDateInput = document.getElementById('end_date');

    function validateDates() {
        var startDate = new Date(startDateInput.value);
        var endDate = new Date(endDateInput.value);

        if (startDate && endDate && startDate > endDate) {
            endDateInput.value = "";
        }
    }

    startDateInput.addEventListener('blur', validateDates);
    endDateInput.addEventListener('blur', validateDates);

    document.querySelector('form').addEventListener('submit', function(event) {
        // Obtén los valores de los campos
        var start_date = document.getElementById('start_date').value;
        var end_date = document.getElementById('end_date').value;
        
        // Conviértelos a objetos Date para comparar
        var startDate = start_date ? new Date(start_date) : null;
        var endDate = end_date ? new Date(end_date) : null;

        // Validación de fechas
        if (startDate && endDate && startDate > endDate) {
            endDateInput.value = "";
        }

    });
    
  </script>

{% endblock %}

decide/users/templates/users/register.html
{% extends "base.html" %}

{% load i18n static %}

{% load static %}
{% block extrahead %}
    <title>Registro de Usuario</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    
{% endblock extrahead %}

{% block content %}
    <div class="navigator">
        <div class="form-container">
            <h2>{% trans "user registration" %}</h2>
            {% if success_message %}
            <div class="alert alert-success">
                {{ success_message }}
            </div>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_username">{% trans "Nombre de usuario" %}</label>
                    <input type="text" id="id_username" name="username" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="id_password">{% trans "Contraseña" %}</label>
                    <input type="password" id="id_password" name="password" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="id_confirm_password">{% trans "Confirmar contraseña" %}</label>
                    <input type="password" id="id_confirm_password" name="confirm_password" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="id_email">{% trans "email(opcional)" %}</label>
                    <input type="email" id="id_email" name="email" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary btn-block">{% trans "Registrate" %}</button>
            </form>
        </div>
    </div>
{% endblock content %}
       

decide/users/templates/users/register_mobile.html
{% extends "base.html" %}
{% load i18n static %}

{% block extrahead %}
    <link type="text/css" rel="stylesheet" href="https://unpkg.com/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link type="text/css" rel="stylesheet" href='{% static "users/style.css" %}' />
{% endblock %}

{% block content %}
    <div id="app-visualizer">

        <h1 class="register-title-mobile">{% trans 'Registrarse' %}</h1>

        <form method="post" class="form-mobile">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_username" class="label-mobile">{% trans "Nombre de usuario %}</label>
                <input type="text" id="id_username" name="username" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_password" class="label-mobile">{% trans "Contraseña" %}</label>
                <input type="password" id="id_password" name="password" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_confirm_password" class="label-mobile">{% trans "Confirmar contraseña %}</label>
                <input type="password" id="id_confirm_password" name="confirm_password" class="form-control">
            </div>
            <div class="form-group">
                <label for="id_email" class="label-mobile">{% trans "email(opcional)" %}</label>
                <input type="email" id="id_email" name="email" class="form-control">
            </div>
            <p class="error-mobile" id="error-message-mobile">{{ error }}</p>
            <button type="submit" class="btn-mobile">{% trans "Registrarte" %}</button>
        </form>

    </div>
{% endblock %}